"""empty message

Revision ID: 8119f78c22e3
Revises: 
Create Date: 2024-01-27 14:52:44.794533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8119f78c22e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_mappings', postgresql.ARRAY(sa.Integer(), dimensions=2), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('ascent', sa.Integer(), nullable=False),
    sa.Column('max_height', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('average_location', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
