# Use an official Python runtime as a parent image
FROM python:3.10.7-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat && rm -rf /var/lib/apt/lists/*

# upgrade pip
RUN pip install --upgrade pip 

# copy the requirements.txt file into the container at /app
COPY requirements.txt ./

# install python dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# copy the rest of the application into the container at /app
COPY . /app

# Run app.py when the container launches
ENTRYPOINT ["sh", "entrypoint.sh"]
CMD ["python", "app.py"]
